import { TodoContextProvider } from '../context/TodoContext';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='bg-slate-900'>
        <TodoContextProvider>
        {children}
        </TodoContextProvider>
      </body>
    </html>
  );
}
